### ISSUE TITLE
example for connecting to outlook.com

### ISSUE THREAD

**Issue by iocast** [xpepermint/smtp-client#1]
thanks for this lib. do you have an example how I can connect for example to

- MTP server name smtp-mail.outlook.com
- SMTP port 587
- SMTP encryption method TLS

and sending out HTML eMails.

I'm always getting the error

`Error: 140391825999744:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:`

**Comment by xpepermint** [comment]
Hey. Not sure about. Make sure you start TLS.
